# Site settings
title: doki doki fm
email: jensen@dokidoki.fm
description: > # this means to ignore newlines until "baseurl:"
  Eclectic curation of Japanese music including electronic, rock, jazz,
  and language lessons.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "dokidoki.fm" # the base hostname & protocol for your site
twitter_username: jensechu
github_username:  jensechu

# Build settings
markdown: kramdown
